# Generated by Django 2.1.1 on 2020-11-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dl_app.Profile')),
            ],
        ),
    ]
