# Generated by Django 2.1.1 on 2020-11-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0002_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='username',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
