# Generated by Django 2.1.1 on 2020-11-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0003_auto_20201116_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='search',
            field=models.CharField(blank=True, default='P-0001', max_length=500),
        ),
    ]
