# Generated by Django 2.1.1 on 2020-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0005_auto_20201116_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=500)),
                ('search', models.CharField(default='P-0001', max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='search_history',
            name='created_at',
        ),
    ]
