# Generated by Django 2.2.1 on 2020-12-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0007_likebutton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likebutton',
            new_name='likebutton1',
        ),
    ]
