# Generated by Django 2.2.1 on 2020-12-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0009_likebutton2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likebutton1',
        ),
        migrations.DeleteModel(
            name='likebutton2',
        ),
    ]
