# Generated by Django 2.2.1 on 2020-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_app', '0010_auto_20201208_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=500)),
                ('search', models.CharField(default='P-0001', max_length=500, null=True)),
            ],
        ),
    ]
